export { LeftImageBlock } from './BlocksWithImages/LeftImageBlock/LeftImageBlock'
export { RightImageBlock } from './BlocksWithImages/RightImageBlock/RightImageBlock'
export { CallButton } from './CallButton/CallButton'
export { Copyright } from './Copyright/Copyright'
export { Footer } from './Footer/Footer'
export { Header } from './Header/Header'
export { Logo } from './Logo/Logo'
export { Slider } from './Slider/Slider'
export type { ImageData } from './Slider/interface'
export { HeadLine } from './HeadLine/HeadLine'
